# Generated by Django 6.0.7 on 2026-08-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChurchInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Grace Community Church', max_length=100)),
                ('motto', models.CharField(default='Growing Together in Faith, Hope, and Love', max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('history', models.TextField(help_text='Church history')),
                ('mission', models.TextField()),
                ('vision', models.TextField()),
                ('core_values', models.TextField(help_text='One value per line')),
                ('pastor_name', models.CharField(max_length=100)),
                ('pastor_title', models.CharField(default='Senior Pastor', max_length=100)),
                ('pastor_message', models.TextField(help_text='Welcome message from the pastor')),
                ('pastor_photo', models.ImageField(blank=True, null=True, upload_to='church/')),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('office_hours', models.TextField(help_text='Office hours, one line per day')),
                ('google_maps_embed', models.TextField(blank=True, help_text='Google Maps iframe embed URL')),
                ('facebook_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('live_stream_url', models.URLField(blank=True, help_text='Live stream URL for Watch Live button')),
            ],
            options={
                'verbose_name': 'Church Information',
                'verbose_name_plural': 'Church Information',
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
