# Generated by Django 6.0.7 on 2026-08-02 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrayerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('request_text', models.TextField()),
                ('is_anonymous', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False, help_text='Share on public prayer wall')),
                ('status', models.CharField(choices=[('new', 'New'), ('praying', 'Being Prayed For'), ('answered', 'Answered'), ('archived', 'Archived')], default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Internal notes (not visible to submitter)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prayer_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
