# Generated by Django 6.0.7 on 2026-08-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeadershipMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('pastor', 'Senior Pastor'), ('associate', 'Associate Pastor'), ('elder', 'Elder'), ('deacon', 'Deacon'), ('worship', 'Worship Leader'), ('youth', 'Youth Pastor'), ('admin', 'Administrator'), ('other', 'Other')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='leadership/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('ministry_type', models.CharField(choices=[('children', "Children's Ministry"), ('youth', 'Youth Ministry'), ('women', "Women's Ministry"), ('men', "Men's Ministry"), ('worship', 'Worship Team'), ('evangelism', 'Evangelism Ministry'), ('outreach', 'Community Outreach'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='ministries/')),
                ('meeting_time', models.CharField(blank=True, max_length=100)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Ministries',
                'ordering': ['order', 'name'],
            },
        ),
    ]
